import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";

// import "./globals.css";

const inter = Inter({subsets:["latin"]});  //inter 폰트사용 알파벳(Latin) 영역 

//웹사이트의 메타데이터(SEO, 검색엔진 최적화 및 브라우저 탭 정보)를 설정하는 객체
export const metadata: Metadata = {
  title: "노원구 맛집 AI 에이전트",
  description: "당신의 행복을 불러올 맛집....추천해드립니다...💙"

}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}
      style={{backgroundColor: "#f4f6f9"}}
      >{children}</body>
    </html>
  );
}



/*
원래 가지고 있던 html관련 설정

 <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>


원래 가지고 있던 폰트 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


*/